[build]
# Directory where your static files (HTML, CSS, JS) are located
publish = "public"

# Directory where your serverless functions are located

# Command to build your frontend (optional, if you're using a build tool like Hugo or Webpack)
# For example, if using Hugo, you'd have:
# command = "hugo"
# If you're not using a build tool, leave this out